### ISSUE TITLE
smartrc.irrp がないときの処理

### ISSUE THREAD

**Issue by muneue-suwa** [dongsiku/SmartRemoteControl2#3]
エラーメッセージ
```
msg: smartrc send hoge
smartrc send hoge
No data file
Traceback (most recent call last):
  File "src/run.py", line 69, in <module>
    bot.main()
  File "src/run.py", line 32, in main
    self.analyze_message(msg[0]["text"])
  File "src/run.py", line 52, in analyze_message
    if splited_msg[2] in self.irrpfile.get_id_list():
  File "/foo/SmartRemoteControl2/src/irrp_file.py", line 27, in get_id_list
    with open(self.get_latest_filename(), "r") as irrp:
TypeError: invalid file: None

```

**Comment by muneue-suwa** [comment]
修正完了
